# **Limpeza e padronização — ENEM 2025**

- **Objetivo:** adequar os tipos de dados, padronizar as colunas textuais e preservar corretamente as categorias e ausências identificadas durante a inspeção.
- **Processo:** registro das métricas iniciais, adequação dos tipos, padronização textual, validação antes e depois das transformações e exportação da base limpa.

In [44]:
## Carregamento das bibliotecas e criação dos caminhos de diretórios

import os
from pathlib import Path
import pandas as pd
import numpy as np
from dotenv import load_dotenv
import pyarrow.parquet as pq
pd.options.display.max_columns = None
pd.options.display.float_format = "{:.3f}".format

load_dotenv()

DATA_DIR = Path(os.environ["ENEM_RAW_DIR"]) / "DADOS"
PARTICIPANTS_FILE = DATA_DIR / "PARTICIPANTES_2025.csv"

In [45]:
participantes_clean = pd.read_csv( PARTICIPANTS_FILE, sep=";" , encoding="latin-1")
participantes_antes = participantes_clean.copy()

In [46]:
# 1 - Registro das métricas de referência antes das transformações
perfil_antes = pd.DataFrame(
    {
        "tipo_antes": participantes_clean.dtypes.astype(str),
        "nulos_antes": participantes_clean.isna().sum(),
        "valores_unicos_antes": participantes_clean.nunique(),
        "valores_duplicados_antes": participantes_clean.duplicated().sum()
    }
)

display(perfil_antes)

,tipo_antes,nulos_antes,valores_unicos_antes,valores_duplicados_antes
NU_INSCRICAO,int64,0,4810772,0
NU_ANO,int64,0,1,0
TP_FAIXA_ETARIA,int64,0,20,0
TP_SEXO,str,0,2,0
TP_ESTADO_CIVIL,int64,0,5,0
TP_COR_RACA,int64,0,6,0
TP_NACIONALIDADE,int64,0,5,0
TP_ST_CONCLUSAO,int64,0,4,0
TP_ANO_CONCLUIU,int64,0,20,0
TP_ENSINO,float64,3080608,2,0
IN_TREINEIRO,int64,0,2,0
CO_MUNICIPIO_PROVA,int64,0,1805,0
NO_MUNICIPIO_PROVA,str,0,1768,0
CO_UF_PROVA,int64,0,27,0
SG_UF_PROVA,str,0,27,0
Q001,str,0,8,0
Q002,str,0,8,0
Q003,str,0,6,0
Q004,str,0,6,0
Q005,int64,0,20,0
Q006,str,0,2,0
Q007,str,0,17,0
Q008,str,0,4,0
Q009,str,0,4,0
Q010,str,0,4,0
Q011,str,0,4,0
Q012,str,0,4,0
Q013,str,0,4,0
Q014,str,0,2,0
Q015,str,0,2,0
Q016,str,0,2,0
Q017,str,0,2,0
Q018,str,0,4,0
Q019,str,0,2,0
Q020,str,0,2,0
Q021,str,0,5,0
Q022,str,0,5,0
Q023,str,0,6,0

In [47]:
## 2 - alteração dos tipos de dados


tipos_esperados = {
    "NU_INSCRICAO": "string",
    "TP_ENSINO": "Int8",
    "CO_MUNICIPIO_PROVA": "string",
    "CO_UF_PROVA": "string",
    "Q005": "int",
}

participantes_clean = participantes_clean.astype(tipos_esperados)

comparacao = pd.DataFrame({
    "antes" : perfil_antes["tipo_antes"],
    "depois" : participantes_clean.dtypes
})

display(comparacao)

## Alteração dos tipos de dados conforme verificação na etapa de inspeção

                      antes  depois
NU_INSCRICAO          int64  string
NU_ANO                int64   int64
TP_FAIXA_ETARIA       int64   int64
TP_SEXO                 str     str
TP_ESTADO_CIVIL       int64   int64
TP_COR_RACA           int64   int64
TP_NACIONALIDADE      int64   int64
TP_ST_CONCLUSAO       int64   int64
TP_ANO_CONCLUIU       int64   int64
TP_ENSINO           float64    Int8
IN_TREINEIRO          int64   int64
CO_MUNICIPIO_PROVA    int64  string
NO_MUNICIPIO_PROVA      str     str
CO_UF_PROVA           int64  string
SG_UF_PROVA             str     str
Q001                    str     str
Q002                    str     str
Q003                    str     str
Q004                    str     str
Q005                  int64   int64
Q006                    str     str
Q007                    str     str
Q008                    str     str
Q009                    str     str
Q010                    str     str
Q011                    str     str
Q012                    str     str
Q013                    str     str
Q014                    str     str
Q015                    str     str
Q016                    str     str
Q017                    str     str
Q018                    str     str
Q019                    str     str
Q020                    str     str
Q021                    str     str
Q022                    str     str
Q023                    str     str

In [48]:

## 3 - padronização das colunas texto

colunas_texto = [
    "NU_INSCRICAO",
    "CO_MUNICIPIO_PROVA",
    "CO_UF_PROVA",
    "NO_MUNICIPIO_PROVA"]

for coluna in colunas_texto:
    participantes_clean[coluna] = (participantes_clean[coluna].str.strip())


## Transformação apenas das colunas texto que poderiam conter espaços indevidos

In [49]:
 ## 4 - validação de nulos e duplicatas aós alterações
perfil_antes = pd.DataFrame({
        "tipo_antes": participantes_antes.dtypes.astype(str),
        "nulos_antes": participantes_antes.isna().sum(),
        "valores_unicos_antes": participantes_antes.nunique(),
        "valores_duplicados_antes": participantes_antes.duplicated().sum()
    })

perfil_depois = pd.DataFrame({
        "tipo_depois": participantes_clean.dtypes.astype(str),
        "nulos_depois": participantes_clean.isna().sum(),
        "valores_unicos_depois": participantes_clean.nunique(),
        "valores_duplicados_depois": participantes_clean.duplicated().sum()
    })

comparacao_perfil = pd.concat([perfil_antes, perfil_depois],axis=1)
display (comparacao_perfil)

## A quantidade de valores nulos e a ausência de duplicatas permaneceu inalterada

,tipo_antes,nulos_antes,valores_unicos_antes,valores_duplicados_antes,tipo_depois,nulos_depois,valores_unicos_depois,valores_duplicados_depois
NU_INSCRICAO,int64,0,4810772,0,string,0,4810772,0
NU_ANO,int64,0,1,0,int64,0,1,0
TP_FAIXA_ETARIA,int64,0,20,0,int64,0,20,0
TP_SEXO,str,0,2,0,str,0,2,0
TP_ESTADO_CIVIL,int64,0,5,0,int64,0,5,0
TP_COR_RACA,int64,0,6,0,int64,0,6,0
TP_NACIONALIDADE,int64,0,5,0,int64,0,5,0
TP_ST_CONCLUSAO,int64,0,4,0,int64,0,4,0
TP_ANO_CONCLUIU,int64,0,20,0,int64,0,20,0
TP_ENSINO,float64,3080608,2,0,Int8,3080608,2,0
IN_TREINEIRO,int64,0,2,0,int64,0,2,0
CO_MUNICIPIO_PROVA,int64,0,1805,0,string,0,1805,0
NO_MUNICIPIO_PROVA,str,0,1768,0,str,0,1768,0
CO_UF_PROVA,int64,0,27,0,string,0,27,0
SG_UF_PROVA,str,0,27,0,str,0,27,0
Q001,str,0,8,0,str,0,8,0
Q002,str,0,8,0,str,0,8,0
Q003,str,0,6,0,str,0,6,0
Q004,str,0,6,0,str,0,6,0
Q005,int64,0,20,0,int64,0,20,0
Q006,str,0,2,0,str,0,2,0
Q007,str,0,17,0,str,0,17,0
Q008,str,0,4,0,str,0,4,0
Q009,str,0,4,0,str,0,4,0
Q010,str,0,4,0,str,0,4,0
Q011,str,0,4,0,str,0,4,0
Q012,str,0,4,0,str,0,4,0
Q013,str,0,4,0,str,0,4,0
Q014,str,0,2,0,str,0,2,0
Q015,str,0,2,0,str,0,2,0
Q016,str,0,2,0,str,0,2,0
Q017,str,0,2,0,str,0,2,0
Q018,str,0,4,0,str,0,4,0
Q019,str,0,2,0,str,0,2,0
Q020,str,0,2,0,str,0,2,0
Q021,str,0,5,0,str,0,5,0
Q022,str,0,5,0,str,0,5,0
Q023,str,0,6,0,str,0,6,0

In [50]:
comparacao_cardinalidade = pd.DataFrame({
    "valores_unicos_antes": perfil_antes["valores_unicos_antes"],
    "valores_unicos_depois": participantes_clean.nunique(),
})

comparacao_cardinalidade["diferenca"] = (
    comparacao_cardinalidade["valores_unicos_depois"]
    - comparacao_cardinalidade["valores_unicos_antes"]
    )

comparacao_cardinalidade

## A cardinalidade dos valores permaneceu inalterada após a limpeza

                    valores_unicos_antes  valores_unicos_depois  diferenca
NU_INSCRICAO                     4810772                4810772          0
NU_ANO                                 1                      1          0
TP_FAIXA_ETARIA                       20                     20          0
TP_SEXO                                2                      2          0
TP_ESTADO_CIVIL                        5                      5          0
TP_COR_RACA                            6                      6          0
TP_NACIONALIDADE                       5                      5          0
TP_ST_CONCLUSAO                        4                      4          0
TP_ANO_CONCLUIU                       20                     20          0
TP_ENSINO                              2                      2          0
IN_TREINEIRO                           2                      2          0
CO_MUNICIPIO_PROVA                  1805                   1805          0
NO_MUNICIPIO_PROVA                  1768                   1768          0
CO_UF_PROVA                           27                     27          0
SG_UF_PROVA                           27                     27          0
Q001                                   8                      8          0
Q002                                   8                      8          0
Q003                                   6                      6          0
Q004                                   6                      6          0
Q005                                  20                     20          0
Q006                                   2                      2          0
Q007                                  17                     17          0
Q008                                   4                      4          0
Q009                                   4                      4          0
Q010                                   4                      4          0
Q011                                   4                      4          0
Q012                                   4                      4          0
Q013                                   4                      4          0
Q014                                   2                      2          0
Q015                                   2                      2          0
Q016                                   2                      2          0
Q017                                   2                      2          0
Q018                                   4                      4          0
Q019                                   2                      2          0
Q020                                   2                      2          0
Q021                                   5                      5          0
Q022                                   5                      5          0
Q023                                   6                      6          0

In [ ]:
# Salvamento dos dados em Parquet

diretorio_atual = Path.cwd()

PROJECT_ROOT = (
diretorio_atual.parent
    if diretorio_atual.name == "notebooks"
    else diretorio_atual
)

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
OUTPUT_FILE = PROCESSED_DIR / "participantes_2025_limpo.parquet"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

participantes_clean.to_parquet(OUTPUT_FILE,engine="pyarrow",compression="snappy",index=False,)


# Base limpa e exportada. Esse formato preserva os tipos de dados, ofereceendo compressão e permitindo leituras mais eficientes do que o CSV original